definitions:
  controllers.AdminLoginRequest:
    properties:
      password:
        type: string
      role:
        type: string
    required:
    - password
    - role
    type: object
  controllers.AdminRequest:
    properties:
      password:
        description: Admin password
        type: string
      role:
        description: Single role for the admin
        type: string
    type: object
  controllers.Credentials:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  controllers.PostCommentInput:
    properties:
      content:
        example: Oroha!!??
        type: string
    type: object
  controllers.PostSuggestionInput:
    properties:
      by:
        description: Example input
        example: 123
        type: integer
      suggestion:
        description: Example input
        example: This is a suggestion
        type: string
      tags:
        description: Example input
        example:
        - '["tag1"'
        - ' "tag2"]'
        items:
          type: string
        type: array
    type: object
  models.Comment:
    properties:
      by:
        type: string
      content:
        type: string
      id:
        description: MongoDB ObjectID
        type: string
      parent:
        type: string
    type: object
  models.Response:
    properties:
      admin:
        description: Admin responding
        type: string
      content:
        description: Response content
        type: string
      created_at:
        description: Timestamp of the response
        type: string
      id:
        type: string
      suggestionId:
        description: Reference to the suggestion
        type: string
    type: object
  models.Suggestion:
    properties:
      by:
        type: string
      content:
        type: string
      createdAt:
        type: string
      id:
        type: string
      parent:
        type: string
      reply:
        type: string
      status:
        type: string
      tags:
        description: Omit if nil
        items:
          type: string
        type: array
      views:
        type: integer
    type: object
  models.User:
    properties:
      password:
        type: string
      regnumber:
        type: integer
      suggestionCount:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin:
    post:
      consumes:
      - application/json
      description: Create a new admin with a role and password
      parameters:
      - description: Admin data
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/controllers.AdminRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new admin
      tags:
      - admins
  /admin/login:
    post:
      consumes:
      - application/json
      description: Login for admin using role and password
      parameters:
      - description: Admin login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/controllers.AdminLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Admin login
      tags:
      - admins
  /admin/suggestions:
    get:
      consumes:
      - application/json
      description: Fetch all suggestions with status "submitted" that are tagged for
        the logged-in admin.
      produces:
      - application/json
      responses:
        "200":
          description: List of suggestions tagged for the admin
          schema:
            items:
              $ref: '#/definitions/models.Suggestion'
            type: array
        "403":
          description: Forbidden - User is not an admin
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve suggestions for admin
      tags:
      - admins
  /admin/suggestions/{suggestionId}/respond:
    post:
      consumes:
      - application/json
      description: Allows an admin to submit a response to a specific suggestion.
      parameters:
      - description: Suggestion ID
        in: path
        name: suggestionId
        required: true
        type: string
      - description: Response content
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/models.Response'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created response
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request - Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden - User is not an admin
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Respond to a suggestion
      tags:
      - admins
  /login:
    post:
      consumes:
      - application/json
      description: Login using username and password
      parameters:
      - description: User credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/controllers.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User login
      tags:
      - users
  /suggestion:
    get:
      description: Get a list of all suggestions in the system
      parameters:
      - description: Bearer JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved suggestions
          schema:
            items:
              $ref: '#/definitions/models.Suggestion'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve all suggestions
      tags:
      - suggestions
    post:
      consumes:
      - application/json
      description: Add a new suggestion for the authenticated user
      parameters:
      - description: Bearer JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Suggestion Details
        in: body
        name: suggestion
        required: true
        schema:
          $ref: '#/definitions/controllers.PostSuggestionInput'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created suggestion
          schema:
            $ref: '#/definitions/models.Suggestion'
        "400":
          description: Bad Request - Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized - Invalid token
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new suggestion
      tags:
      - suggestions
  /suggestion/{suggestionId}/comments:
    get:
      consumes:
      - application/json
      description: Retrieves all comments associated with a specific suggestion ID.
      parameters:
      - description: Suggestion ID
        in: path
        name: suggestionId
        required: true
        type: string
      - description: Bearer token for authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of comments with selected fields only
          schema:
            items:
              $ref: '#/definitions/models.Comment'
            type: array
        "400":
          description: Bad Request - Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found - No comments found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get comments for a suggestion
      tags:
      - suggestions
  /suggestion/comment/{suggestionId}:
    post:
      consumes:
      - application/json
      description: Add a new comment to a suggestion or another comment
      parameters:
      - description: Bearer JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Parent Suggestion or Comment ID
        in: path
        name: suggestionId
        required: true
        type: string
      - description: Comment Details
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/controllers.PostCommentInput'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created comment
          schema:
            $ref: '#/definitions/models.Suggestion'
        "400":
          description: Bad Request - Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized - Invalid token
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Parent not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add a new comment
      tags:
      - suggestions
  /suggestion/tag/{role}:
    get:
      description: Retrieve suggestions filtered by a specific tag or role
      parameters:
      - description: Role/Tag
        in: path
        name: role
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved suggestions
          schema:
            items:
              $ref: '#/definitions/models.Suggestion'
            type: array
        "400":
          description: Bad Request - Missing role
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: No suggestions found for the tag
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get suggestions by tag/role
      tags:
      - suggestions
  /suggestion/user/{username}:
    get:
      description: Retrieve all suggestions submitted by a specific user
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved user suggestions
          schema:
            items:
              $ref: '#/definitions/models.Suggestion'
            type: array
        "400":
          description: Bad Request - Missing username
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get suggestions by username
      tags:
      - suggestions
  /suggestion/vote/{type}:
    post:
      consumes:
      - application/json
      description: Allows a user to upvote or downvote a suggestion. If the user has
        already voted, it will update the vote type.
      parameters:
      - description: Vote type (upvote or downvote)
        in: path
        name: type
        required: true
        type: string
      - description: Bearer token for authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Vote data with suggestion ID
        in: body
        name: vote
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Successfully added or updated vote
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request body or vote type
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Username missing in claims, or suggestion not found
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: You have already voted with the same type
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add or update a vote on a suggestion
      tags:
      - votes
  /suggestions/count:
    get:
      description: Returns the number of suggestions made by the user and how many
        they can still make
      parameters:
      - description: Bearer JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: User's suggestion count and remaining allowed suggestions
          schema:
            additionalProperties:
              type: integer
            type: object
        "401":
          description: Unauthorized - Invalid token
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user's suggestion count and remaining allowed suggestions
      tags:
      - suggestions
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user with username, registration number, and password
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: 'Conflict: User already exists'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new user
      tags:
      - users
swagger: "2.0"
